language: node_js
node_js:
  - 8.9.3
install:
  - npm i -g ganache-cli codecov
  - npm install
script:
  - npm run lint
  - ./node_modules/.bin/run-with-testrpc './node_modules/.bin/truffle migrate'
  - ./node_modules/.bin/run-with-testrpc './node_modules/.bin/truffle test'
  - npm run coverage
  - codecov
